nome = input('Digite seu nome completo: ').strip()
print('Analisando seu nome...')
print('Seu nome em letras maiúsculas é {}.'.format(nome.upper()))
print('Seu nome em letras minúsculas é {}.'.format(nome.lower()))
print('Seu nome ao todo tem {} letras.'.format(len(nome) - nome.count(' ')))
separa = nome.split()
print('Seu nome é {} e tem {} letras.'.format(separa[0], len(separa[0])))
# print('Seu primeiro nome tem {} letras.'.format(nome.find(' ')))
